---
- hosts: nodes
# sudo: True
  remote_user: arctiqadmin
  become: True
  become_method: sudo
  vars:
    docker_storage_mount: /dev/sdc

  vars_prompt:
    - name: "rhn_user_name" 
      prompt: "RHN UserName ?"      
    - name: "rhn_password" 
      prompt: "RHN Password ?"      
    - name: "rhel_pool_id"
      prompt: "RHN POOL ID ?"
      
  tasks:

#  - name: Add hosts entries to be able to connect to RHN. Needed only on OS1
#    blockinfile: 
#      dest: /etc/hosts
#      content: |
#        209.132.183.44          xmlrpc.rhn.redhat.com
#        23.204.148.218               content-xmlrpc.rhn.redhat.com
#        209.132.183.49              subscription.rhn.redhat.com
#        209.132.182.33 repository.jboss.org
#        209.132.182.63 registry.access.redhat.com

  - name: Force unregister before register
    redhat_subscription:
      state: absent
    ignore_errors: true
  
  - name: register node with subscription-manager
    redhat_subscription: state=present username="{{ rhn_user_name }}" password="{{ rhn_password }}" autosubscribe=false
    register: task_result
    until: task_result | succeeded
    retries: 10
    delay: 5
  
  - name: attach node to subscription pool
    command: subscription-manager attach --pool {{ item }}
    register: task_result
    until: task_result.rc == 0
    retries: 10
    delay: 1
    ignore_errors: no
    with_items: '{{rhel_pool_id}}'

  - name: Enable only required repositories with Subscription Manager
    command: subscription-manager repos --disable="*" --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.4-rpms"

  - name: Run yum update
    yum: name=* state=latest

  - yum: name=wget state=latest
  - yum: name=vim-enhanced state=latest
  - yum: name=net-tools state=latest
  - yum: name=bind-utils state=latest
  - yum: name=git state=latest
  - yum: name=iptables-services state=latest
  - yum: name=bridge-utils state=latest
  - yum: name=bash-completion state=latest
  - yum: name=atomic-openshift-utils state=latest
  - yum: name=atomic-openshift-excluder state=latest
  - yum: name=atomic-openshift-docker-excluder state=latest


  - name: Unexclude atomic-openshift package for the duration of the install
    command: atomic-openshift-excluder unexclude 
